### ISSUE TITLE
论文中的疑惑

### ISSUE THREAD

**Issue by Fengww2014** [liuaishan/ModelBiasedAttack#1]
![图片](https://user-images.githubusercontent.com/30151004/87011816-fdaa4280-c1fa-11ea-8fc5-c7d2d8d713f8.png)
你好同学，论文中这个式子该怎么理解。下面有我的几个在看文章时不太理解的地方。麻烦解惑谢谢

- [x] I是argmax优化后的结果，还是最优解x的值，

- [x] 这I_t是不是标志他是最能代表类别t的一个图片原型，那这个为什么s_t是负号，然后最大化，不应该是正号吗？

- [x] 还有就是I‘和I是通过location mask和一个patch合成的，这个location mask怎么保证他不同的位置对优化的结果没有影响

**Comment by liuaishan** [comment]
1、I_t就是优化生成的prototype
2、I_t是指最能代表t类别的一个图片原型。为了取得更好的效果，我们这里直接采用了MultiMarginLoss，其定义就是这样。
3、没有太明白你的问题的含义。我们将patch和I合并在一起，形成adversarial example I'来训练优化patch的像素值，这中间加入了EOT来进行多个位置的expectation的优化，使得其具有更好地攻击性。

**Comment by liuaishan** [comment]
问题2：公式应该是argmin
